### ISSUE TITLE
Dead players can be looted

### ISSUE THREAD

**Issue by mktheplug** [rdopaa/ox_thief#9]
Got the issue wrong before my bad,

Players who have died can still be looted without hands up

**Comment by rdopaa** [comment]
Yes the idea is that you can loot people died or with handsup.

**Comment by mktheplug** [comment]
Yes please if you can it would be great brother

**Comment by rdopaa** [comment]
Done. Test it and tell me.

**Comment by mktheplug** [comment]
Works perfect, thanks
